//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPlug.Ext.Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPlug.Ext.Demo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;section class=&quot;row-fluid&quot;&gt;&lt;h2&gt;Extensions Demonstration&lt;/h2&gt;&lt;/section&gt;
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///  
        ///    &lt;h3 class=&quot;box-header&quot;&gt;
        ///        IFTTT Timer
        ///    &lt;/h3&gt;
        ///    &lt;div class=&quot;box&quot;&gt;
        ///        &lt;div class=&quot;span2&quot;&gt;
        ///            &lt;p&gt;
        ///                &lt;button id=&quot;start-timer&quot; class=&quot;btn btn-large btn-green&quot; type=&quot;button&quot;&gt;Start&lt;/button&gt;
        ///            &lt;/p&gt;
        ///            &lt;p&gt;
        ///                &lt;button id=&quot;stop-timer&quot; class=&quot;btn btn-large btn-red&quot; type=&quot;button&quot;&gt;Stop&lt;/button&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DemoDashboardApp3_cshtml {
            get {
                return ResourceManager.GetString("DemoDashboardApp3_cshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;div class=&quot;span12&quot;&gt;
        ///                &lt;p style=&quot;font-size:26px; line-height: 54px; text-align: center; margin: 0px;&quot;&gt;Event Trace&lt;/p&gt;
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;div class=&quot;row-fluid&quot; id=&quot;EventList&quot;&gt;
        ///            &lt;/div&gt;
        ///
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventTrace_cshtml {
            get {
                return ResourceManager.GetString("EventTrace_cshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;div class=&quot;span12&quot;&gt;
        ///                &lt;p style=&quot;font-size:26px; line-height: 54px; text-align: center; margin: 0px;&quot;&gt;Upload File Example&lt;/p&gt;
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;h4&gt;Upload File&lt;/h4&gt;
        ///            &lt;div class=&quot;row-fluid well&quot;&gt;
        ///                &lt;p&gt;Upload a file here.&lt;/p&gt;
        ///
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleFileUpload_cshtml {
            get {
                return ResourceManager.GetString("ExampleFileUpload_cshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;base href=&quot;@Model.Context.Paths.Base&quot;&gt;
        ///
        ///    &lt;script src=&quot;@Raw(Model.Context.Paths.Roots.Assets)multiplug.ext.mplib/scripts/websocket.min.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;stream/hubs&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;@Raw(Model.Context.Paths.Roots.Assets)multiplug.ext.mplib/scripts/multiplug.js?id=@Model.Context.WebS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Home_cshtml {
            get {
                return ResourceManager.GetString("Home_cshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// Material Components for the Web
        /// Copyright (c) 2018 Google Inc.
        /// License: Apache-2.0
        ///*/
        ///@-webkit-keyframes mdc-ripple-fg-radius-in{0%{-webkit-animation-timing-function:cubic-bezier(.4,0,.2,1);animation-timing-function:cubic-bezier(.4,0,.2,1);-webkit-transform:translate(var(--mdc-ripple-fg-translate-start,0)) scale(1);transform:translate(var(--mdc-ripple-fg-translate-start,0)) scale(1)}to{-webkit-transform:translate(var(--mdc-ripple-fg-translate-end,0)) scale(var(--mdc-ripple-fg-scale,1));transform [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string material_components_web_min_css {
            get {
                return ResourceManager.GetString("material_components_web_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// Material Components for the Web
        /// Copyright (c) 2018 Google Inc.
        /// License: Apache-2.0
        ///*/
        ///!function (t, e) { &quot;object&quot; == typeof exports &amp;&amp; &quot;object&quot; == typeof module ? module.exports = e() : &quot;function&quot; == typeof define &amp;&amp; define.amd ? define([], e) : &quot;object&quot; == typeof exports ? exports.mdc = e() : t.mdc = e() }(this, function () {
        ///    return function (t) { function e(r) { if (n[r]) return n[r].exports; var i = n[r] = { i: r, l: !1, exports: {} }; return t[r].call(i.exports, i, i.exports, e), i.l =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string material_components_web_min_js {
            get {
                return ResourceManager.GetString("material_components_web_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;base href=&quot;@Model.Context.Paths.Base&quot;&gt;
        ///
        ///    &lt;script src=&quot;@Raw(Model.Context.Paths.Roots.Assets)multiplug.ext.mplib/scripts/jquery-1.10.2.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;@Raw(Model.Context.Paths.Roots.Assets)multiplug.ext.mplib/scripts/websocket.min.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;stream/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectorApp {
            get {
                return ResourceManager.GetString("ProjectorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;form action=&quot;&quot; method=&quot;post&quot; accept-charset=&quot;utf-8&quot; enctype=&quot;application/x-www-form-urlencoded&quot;&gt;
        ///    &lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///        &lt;div class=&quot;row-fluid&quot;&gt;
        ///            &lt;div class=&quot;box&quot;&gt;
        ///                &lt;div class=&quot;span2&quot;&gt;
        ///                &lt;/div&gt;
        ///                &lt;div class=&quot;span8&quot;&gt;
        ///                    &lt;p style=&quot;font-size:26px; line-height: 54px; text-align: center; margin: 0px;&quot;&gt;Event Trace Subscriptions&lt;/p&gt;
        ///                &lt;/div&gt;
        ///                &lt;div cla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsEventTrace_cshtml {
            get {
                return ResourceManager.GetString("SettingsEventTrace_cshtml", resourceCulture);
            }
        }
    }
}
